using EdgeDB.QueryNodes;
using EdgeDB.Schema;

namespace EdgeDB;

internal sealed record CompileContext
{
    public bool IncludeGlobalsInQuery { get; init; } = true;
    public bool IncludeAutogeneratedNodes { get; init; } = true;
    public bool RunReducers { get; set; } = true;
    public Action<QueryNode>? PreFinalizerModifier { get; init; }
    public bool Debug { get; init; }
    public SchemaInfo? SchemaInfo { get; init; }

    public static CompileContext SubQueryContext(SchemaInfo? schemaInfo, Action<QueryNode>? finalizer, bool debug) =>
        new()
        {
            SchemaInfo = schemaInfo,
            RunReducers = false,
            IncludeAutogeneratedNodes = false,
            PreFinalizerModifier = finalizer,
            Debug = debug,
            IncludeGlobalsInQuery = false
        };
}
