using EdgeDB.QueryNodes;
using EdgeDB.Schema;

namespace EdgeDB;

internal sealed record CompileContext
{
    public bool IncludeGlobalsInQuery { get; init; } = true;
    public bool IncludeAutogeneratedNodes { get; init; } = true;
    public Action<QueryNode>? PreFinalizerModifier { get; init; }
    public bool Debug { get; init; }
    public SchemaInfo? SchemaInfo { get; init; }
}
