using EdgeDB.Builders;
using EdgeDB.Compiled;
using EdgeDB.Interfaces;
using EdgeDB.Interfaces.Queries;
using EdgeDB.QueryNodes;
using EdgeDB.Schema;
using System.Linq.Expressions;

namespace EdgeDB
{
    /// <summary>
    ///     Represents a generic query builder for querying against <typeparamref name="TType"/>.
    /// </summary>
    /// <typeparam name="TType">The type of which queries will be preformed with.</typeparam>
    /// <typeparam name="TContext">The type of context representing the current builder.</typeparam>
    public interface IQueryBuilder<TType, TContext> :
        IQueryBuilder,
        ISelectQuery<TType, TContext>,
        IUpdateQuery<TType, TContext>,
        IDeleteQuery<TType, TContext>,
        IInsertQuery<TType, TContext>,
        IUnlessConflictOn<TType, TContext>,
        IGroupQuery<TType, TContext>,
        IGroupUsingQuery<TType, TContext>
        where TContext : IQueryContext
    {
        IGroupQuery<TType, TContext> Group();

        IGroupQuery<TResult, TContext> Group<TResult>(Action<ShapeBuilder<TResult>> shape);

        IGroupQuery<TResult, TContext> Group<TResult>(Expression<Func<TResult>> selector);
        IGroupQuery<TResult, TContext> Group<TResult>(Expression<Func<TContext, TResult>> selector);
        IGroupQuery<TResult, TContext> Group<TResult>(Expression<Func<TResult>> selector, Action<ShapeBuilder<TResult>> shape);
        IGroupQuery<TResult, TContext> Group<TResult>(Expression<Func<TContext, TResult>> selector, Action<ShapeBuilder<TResult>> shape);

        internal IGroupQuery<TResult, TNewContext> GroupInternal<TResult, TNewContext>(LambdaExpression? selector = null,
            Action<ShapeBuilder<TResult>>? shape = null
        ) where TNewContext : IQueryContextSelf<TResult>;

        /// <summary>
        ///     Adds a <c>FOR</c> statement on the <paramref name="collection"/> with a <c>UNION</c>
        ///     whos inner query is the <paramref name="iterator"/>.
        /// </summary>
        /// <param name="collection">The collection to iterate over.</param>
        /// <param name="iterator">The iterator for the <c>UNION</c> statement.</param>
        ///  <typeparam name="U">The type of the collection.</typeparam>
        ///  <typeparam name="TNew">The type returned from the iterator query.</typeparam>
        /// <returns>The current query.</returns>
        IMultiCardinalityExecutable<TNew> For<U, TNew>(IEnumerable<U> collection, Expression<Func<JsonCollectionVariable<U>, IQuery<TNew>>> iterator);

        /// <summary>
        ///     Adds a <c>FOR</c> statement on the <paramref name="collection"/> with a <c>UNION</c>
        ///     whos inner query is the <paramref name="iterator"/>.
        /// </summary>
        /// <param name="collection">The collection to iterate over.</param>
        /// <param name="iterator">The iterator for the <c>UNION</c> statement.</param>
        ///  <typeparam name="U">The type of the collection.</typeparam>
        ///  <typeparam name="TNew">The type returned from the iterator query.</typeparam>
        /// <returns>The current query.</returns>
        IMultiCardinalityExecutable<TNew> For<U, TNew>(Expression<Func<TContext, IEnumerable<U>>> collection, Expression<Func<JsonCollectionVariable<U>, IQuery<TNew>>> iterator);


        /// <summary>
        ///     Adds a <c>WITH</c> statement whos variables are the properties defined in <paramref name="variables"/>.
        /// </summary>
        /// <typeparam name="TVariables">The type whos properties will be used as variables.</typeparam>
        /// <param name="variables">
        ///     The instance whos properties will be extrapolated as variables for the query builder.
        /// </param>
        /// <returns>
        ///     The current query.
        /// </returns>
        IQueryBuilder<TType, QueryContextSelfVars<TType, TVariables>> With<TVariables>(TVariables variables);

        /// <summary>
        ///     Adds a <c>WITH</c> statement whos variables are the properties defined in <paramref name="variables"/>.
        /// </summary>
        /// <typeparam name="TVariables">The type whos properties will be used as variables.</typeparam>
        /// <param name="variables">
        ///     The instance whos properties will be extrapolated as variables for the query builder.
        /// </param>
        /// <returns>
        ///     The current query.
        /// </returns>
        IQueryBuilder<TType, QueryContextSelfVars<TType, TVariables>> With<TVariables>(Expression<Func<QueryContextSelf<TType>, TVariables>> variables);

        /// <summary>
        ///     Adds a <c>SELECT</c> statement selecting the current <typeparamref name="TType"/> with an
        ///     autogenerated shape.
        /// </summary>
        /// <returns>
        ///     A <see cref="ISelectQuery{TType, TContext}"/>.
        /// </returns>
        ISelectQuery<TType, TContext> Select();

        /// <summary>
        ///     Adds a <c>SELECT</c> statement selecting <typeparamref name="TResult"/> with an
        ///     autogenerated shape.
        /// </summary>
        /// <returns>
        ///     A <see cref="ISelectQuery{TResult, TContext}"/>.
        /// </returns>
        ISelectQuery<TResult, TContext> Select<TResult>();

        /// <summary>
        ///     Adds a <c>SELECT</c> statement selecting the provided expression.
        /// </summary>
        /// <typeparam name="TResult">The return result of the select expression.</typeparam>
        /// <param name="shape">A delegate to build the shape for selecting <typeparamref name="TResult"/>.</param>
        /// <returns>
        ///     A <see cref="ISelectQuery{TType, TContext}"/>.
        /// </returns>
        ISelectQuery<TResult, TContext> Select<TResult>(Action<ShapeBuilder<TResult>> shape);

        internal ISelectQuery<TResult, TNewContext> SelectInternal<TResult, TNewContext>(Action<ShapeBuilder<TResult>>? shape = null)
            where TNewContext : IQueryContextSelf<TResult>;

        /// <summary>
        ///     Adds a <c>SELECT</c> statement, selecting the result of a <paramref name="expression"/>.
        /// </summary>
        /// <typeparam name="TNewType">The resulting type of the expression.</typeparam>
        /// <param name="expression">The expression on which to select.</param>
        /// <returns>
        ///     A <see cref="ISelectQuery{TNewType, TContext}"/>.
        /// </returns>
        ISelectQuery<TNewType, TContext> SelectExpression<TNewType>(Expression<Func<TNewType?>> expression);

        /// <summary>
        ///     Adds a <c>SELECT</c> statement, selecting the result of a <paramref name="expression"/>.
        /// </summary>
        /// <typeparam name="TNewType">The resulting type of the expression.</typeparam>
        /// <param name="expression">The expression on which to select.</param>
        /// <returns>
        ///     A <see cref="ISelectQuery{TNewType, TContext}"/>.
        /// </returns>
        ISelectQuery<TNewType, TContext> SelectExpression<TNewType>(Expression<Func<TContext, TNewType?>> expression);

        /// <summary>
        ///     Adds a <c>SELECT</c> statement, selecting the result of a <paramref name="expression"/>.
        /// </summary>
        /// <typeparam name="TNewType">The resulting type of the expression.</typeparam>
        /// <param name="expression">The expression on which to select.</param>
        /// <param name="shape">A optional delegate to build the shape for selecting <typeparamref name="TNewType"/>.</param>
        /// <returns>
        ///     A <see cref="ISelectQuery{TNewType, TContext}"/>.
        /// </returns>
        ISelectQuery<TNewType, TContext> SelectExpression<TNewType>(Expression<Func<TContext, TNewType>> expression,
            Action<ShapeBuilder<TNewType>>? shape);

        /// <summary>
        ///     Adds a <c>SELECT</c> statement, selecting the result of a <paramref name="expression"/>.
        /// </summary>
        /// <typeparam name="TExpression">The resulting type of the expression.</typeparam>
        /// <typeparam name="TShape">The shape result of <typeparamref name="TExpression"/>.</typeparam>
        /// <param name="expression">The expression on which to select.</param>
        /// <param name="shape">A optional delegate to build the shape for selecting <typeparamref name="TExpression"/>.</param>
        /// <returns>
        ///     A <see cref="ISelectQuery{TNewType, TContext}"/>.
        /// </returns>
        ISelectQuery<TShape, TContext> SelectExpression<TExpression, TShape>(
            Expression<Func<TContext, TExpression>> expression,
            Func<ShapeBuilder<TExpression>, ShapeBuilder<TExpression, TShape>>? shape = null
        );

        // TODO: is this needed?
        // internal ISelectQuery<TNew, TNewContext> SelectExpressionInternal<TNew, TNewContext>(LambdaExpression expression, Action<ShapeBuilder<TNew>>? shape = null)
        //     where TNewContext : IQueryContextSelf<TNew>;

        /// <summary>
        ///     Adds a <c>INSERT</c> statement inserting an instance of <typeparamref name="TType"/>.
        /// </summary>
        /// <remarks>
        ///     This statement requires introspection when <typeparamref name="TType"/> contains a
        ///     property thats a <see cref="ValueType"/>.
        /// </remarks>
        /// <param name="value">The value to insert.</param>
        /// <param name="returnInsertedValue">
        ///     whether or not to implicitly add a select statement to return the inserted value.
        /// </param>
        /// <returns>A <see cref="IInsertQuery{TType, TContext}"/>.</returns>
        IInsertQuery<TNew, TContext> Insert<TNew>(TNew value, bool returnInsertedValue);

        /// <summary>
        ///     Adds a <c>INSERT</c> statement inserting an instance of <typeparamref name="TType"/>.
        /// </summary>
        /// <remarks>
        ///     This statement requires introspection when <typeparamref name="TType"/> contains a
        ///     property thats a <see cref="ValueType"/>.
        /// </remarks>
        /// <param name="value">The value to insert.</param>
        /// <returns>A <see cref="IInsertQuery{TType, TContext}"/>.</returns>
        IInsertQuery<TNew, TContext> Insert<TNew>(TNew value);

        /// <summary>
        ///     Adds a <c>INSERT</c> statement inserting an instance of <typeparamref name="TType"/>.
        /// </summary>
        /// <remarks>
        ///     This statement requires introspection when <typeparamref name="TType"/> contains a
        ///     property thats a <see cref="ValueType"/>.
        /// </remarks>
        /// <param name="value">The callback containing the value initialization to insert.</param>
        /// <param name="returnInsertedValue">
        ///     whether or not to implicitly add a select statement to return the inserted value.
        /// </param>
        /// <returns>A <see cref="IInsertQuery{TType, TContext}"/>.</returns>
        IInsertQuery<TNew, TContext> Insert<TNew>(Expression<Func<TContext, TNew>> value, bool returnInsertedValue);

        /// <summary>
        ///     Adds a <c>INSERT</c> statement inserting an instance of <typeparamref name="TType"/>.
        /// </summary>
        /// <remarks>
        ///     This statement requires introspection when <typeparamref name="TType"/> contains a
        ///     property thats a <see cref="ValueType"/>.
        /// </remarks>
        /// <param name="value">The callback containing the value initialization to insert.</param>
        /// <returns>A <see cref="IInsertQuery{TType, TContext}"/>.</returns>
        IInsertQuery<TNew, TContext> Insert<TNew>(Expression<Func<TContext, TNew>> value);

        /// <summary>
        ///     Adds a <c>UPDATE</c> statement updating an instance of <typeparamref name="TType"/>.
        /// </summary>
        /// <param name="selector">
        ///     A function to select the target for the update.
        /// </param>
        /// <param name="returnUpdatedValue">
        ///     whether or not to implicitly add a select statement to return the inserted value.
        /// </param>
        /// <returns>A <see cref="IUpdateQuery{TType, TContext}"/>.</returns>
        IUpdateQuery<TSelected, TContext> Update<TSelected>(Expression<Func<TType, TContext, TSelected>> selector, bool returnUpdatedValue);

        /// <summary>
        ///     Adds a <c>UPDATE</c> statement updating an instance of <typeparamref name="TType"/>.
        /// </summary>
        /// <param name="selector">
        ///     A function to select the target for the update.
        /// </param>
        /// <returns>A <see cref="IUpdateQuery{TType, TContext}"/>.</returns>
        IUpdateQuery<TSelected, TContext> Update<TSelected>(Expression<Func<TType, TSelected>> selector);

        /// <summary>
        ///     Adds a <c>UPDATE</c> statement updating an instance of <typeparamref name="TType"/>.
        /// </summary>
        /// <returns>A <see cref="IUpdateQuery{TType, TContext}"/>.</returns>
        IUpdateQuery<TSelected, TContext> Update<TSelected>();

        /// <summary>
        ///     Adds a <c>DELETE</c> statement deleting an instance of <typeparamref name="TType"/>.
        /// </summary>
        IDeleteQuery<TType, TContext> Delete();

        /// <summary>
        ///     Adds a <c>DELETE</c> statement deleting an instance of <typeparamref name="TType"/>.
        /// </summary>
        /// <typeparam name="TNewType">The type to delete.</typeparam>
        IDeleteQuery<TNewType, TContext> Delete<TNewType>();

        internal IDeleteQuery<TResult, TNewContext> DeleteInternal<TResult, TNewContext>()
            where TNewContext : IQueryContextSelf<TResult>;
    }

    /// <summary>
    ///     Represents a generic query builder with a build function.
    /// </summary>
    public interface IQueryBuilder
    {
        /// <summary>
        ///     Gets whether or not this query builder requires introspection to build.
        /// </summary>
        public bool RequiresIntrospection { get; }

        /// <summary>
        ///     Gets a read-only collection of query nodes within this query builder.
        /// </summary>
        internal IReadOnlyCollection<QueryNode> Nodes { get; }

        /// <summary>
        ///     Gets a read-only collection of globals defined within this query builder.
        /// </summary>
        internal List<QueryGlobal> Globals { get; }

        /// <summary>
        ///     Gets a read-only dictionary of query variables defined within the query builder.
        /// </summary>
        internal Dictionary<string, object?> Variables { get; }

        internal SchemaInfo? SchemaInfo { get; }

        /// <summary>
        ///     Compiles the current query.
        /// </summary>
        /// <remarks>
        ///     If the query requires introspection please use
        ///     <see cref="CompileAsync"/>.
        /// </remarks>
        /// <param name="debug">Whether or not to compile the query in a debug fashion, returning a <see cref="DebugCompiledQuery"/>.</param>
        /// <returns>
        ///     A <see cref="CompiledQuery"/>.
        /// </returns>
        CompiledQuery Compile(bool debug = false);

        /// <summary>
        ///     Compiles the current query asynchronously, allowing database introspection.
        /// </summary>
        /// <param name="edgedb">The client to preform introspection with.</param>
        /// <param name="debug">Whether or not to compile the query in a debug fashion, returning a <see cref="DebugCompiledQuery"/>.</param>
        /// <param name="token">A cancellation token to cancel the asynchronous operation.</param>
        /// <returns>A <see cref="CompiledQuery"/>.</returns>
        ValueTask<CompiledQuery> CompileAsync(IEdgeDBQueryable edgedb, bool debug = false, CancellationToken token = default);

        internal void CompileInternal(QueryWriter writer, CompileContext? context = null);
    }
}
