using EdgeDB.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace EdgeDB.CLI.Utils
{
    /// <summary>
    ///     A utility class containing methods related to hashes.
    /// </summary>
    internal static class HashUtils
    {
        /// <summary>
        ///     Hashes edgeql for an autogenerated file header.
        /// </summary>
        /// <param name="edgeql">The edgeql to hash.</param>
        /// <returns>The hashed edgeql as hex.</returns>
        public static string HashEdgeQL(string edgeql)
        {
            using var algo = SHA256.Create();
            return HexConverter.ToHex(algo.ComputeHash(Encoding.UTF8.GetBytes(edgeql)));
        }
    }
}
