// AUTOGENERATED: DO NOT MODIFY
// GENHASH:84480B9D4D6CDEB7C2EA642ED3D274AE24294C26E4E72643CA97A518FC073F3D
// Generated on 2022-12-06T21:23:52.5994004Z

using EdgeDB;
using System;

namespace EdgeDB.Generated;

#nullable enable
[EdgeDBType]
public partial class CreateUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }
}
#nullable restore
