// AUTOGENERATED: DO NOT MODIFY
// Generated on 2022-12-02T18:36:19.4242140Z

using EdgeDB;
using System;

namespace EdgeDB.Generated;

#nullable enable
[EdgeDBType]
public class CreateUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }
}
#nullable restore
