// AUTOGENERATED: DO NOT MODIFY
// GENHASH:426ED2B8187E87B62120CFA458501AF2966E7721D2D80E09C643D49F389B2028
// Generated on 2022-12-06T21:23:52.6080765Z

using EdgeDB;
using System;

namespace EdgeDB.Generated;

#nullable enable
[EdgeDBType]
public partial class DeleteUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }
}
#nullable restore
