// AUTOGENERATED: DO NOT MODIFY
// GENHASH:D68E7CCBD0DF1D3C7F777CFDCEEAB08927B96A35FFE7E926CAF5C0333ED16ADD
// Generated on 2022-12-06T21:23:52.6108296Z

using EdgeDB;
using System;

namespace EdgeDB.Generated;

#nullable enable
[EdgeDBType]
public partial class GetUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }

    [EdgeDBProperty("name")]
    public string? Name { get; set; }

    [EdgeDBProperty("email")]
    public string? Email { get; set; }
}
#nullable restore
