// AUTOGENERATED: DO NOT MODIFY
// GENHASH:DEACD7E2C104BB976F65EDE2AA683ACEAF9A501829B3BBC8EB11AB4E1F4D23E0
// Generated on 2022-12-06T21:23:52.6135865Z

using EdgeDB;
using System;

namespace EdgeDB.Generated;

#nullable enable
[EdgeDBType]
public partial class UpdateUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }
}
#nullable restore
