// AUTOGENERATED: DO NOT MODIFY
// GENHASH:651795FB426E969E977054350F9254A5689A603E2CEDF9E34A8DC377BE0DE458
// Generated on 2022-12-06T20:36:05.1457189Z

using EdgeDB;
using System;

namespace EdgeDB.Generated;

#nullable enable
[EdgeDBType]
public partial class UserModel
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }
}
#nullable restore
