// AUTOGENERATED: DO NOT MODIFY
// edgeql:B9692A5CA0A9992246361197BEACBDE398A5A30C5DCCC83BCACD8C80D5842FEB
// Generated on 2023-07-18T17:34:30.4467394Z
#nullable enable
using EdgeDB;

namespace EdgeDB.Generated;

public static class CreateUser
{
    /// <summary>
    ///     The string containing the query defined in <c>C:\Users\lynch\source\repos\EdgeDB\examples\EdgeDB.Examples.GenerationExample\Scripts\CreateUser.edgeql</c>.
    /// </summary>
    public const string QUERY =
"""
INSERT Person {
  name := <str>$name,
  email := <str>$email
}
UNLESS CONFLICT ON .email 
ELSE (SELECT Person)
""";

    /// <summary>
    ///     Executes the CreateUser query, defined as:
    ///     <code>
    ///         INSERT Person {
    ///           name := &lt;str&gt;$name,
    ///           email := &lt;str&gt;$email
    ///         }
    ///         UNLESS CONFLICT ON .email 
    ///         ELSE (SELECT Person)
    ///     </code>
    /// </summary>
    /// <param name="client">The client to execute the query on.</param>
    /// <param name="name">The name parameter in the query.</param>
    /// <param name="email">The email parameter in the query.</param>
    public static Task<CreateUserResult> ExecuteAsync(IEdgeDBQueryable client, String name, String email, CancellationToken token = default)
        => client.QueryRequiredSingleAsync<CreateUserResult>(
            QUERY, new Dictionary<string, object?>() { { "name", name }, { "email", email } },
            capabilities: Capabilities.Modifications, token: token
        );

    /// <summary>
    ///     Executes the CreateUser query, defined as:
    ///     <code>
    ///         INSERT Person {
    ///           name := &lt;str&gt;$name,
    ///           email := &lt;str&gt;$email
    ///         }
    ///         UNLESS CONFLICT ON .email 
    ///         ELSE (SELECT Person)
    ///     </code>
    /// </summary>
    /// <param name="client">The client to execute the query on.</param>
    /// <param name="name">The name parameter in the query.</param>
    /// <param name="email">The email parameter in the query.</param>
    public static Task<CreateUserResult> CreateUserAsync(this IEdgeDBQueryable client, String name, String email, CancellationToken token = default)
        => ExecuteAsync(client, name, email, token: token);
}
#nullable restore