// AUTOGENERATED: DO NOT MODIFY
// edgeql:8F4282FFB3ADCA549B2F18362FAE328971409954B3CFA1B28AD5CCE1F74156AC
// Generated on 2023-07-24T15:15:21.9231397Z
#nullable enable
using EdgeDB;
using EdgeDB.DataTypes;

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace EdgeDB.Generated;

public static class DeleteUser
{
    /// <summary>
    ///     The string containing the query defined in <c>C:\Users\lynch\source\repos\EdgeDB\examples\EdgeDB.Examples.GenerationExample\Scripts\DeleteUser.edgeql</c>.
    /// </summary>
    public static readonly string Query;
    private static readonly string _queryHex = "44454C45544520506572736F6E200D0A46494C544552202E656D61696C203D203C7374723E24656D61696C";


    static DeleteUser()
    {
        Query = string.Join("", Regex.Split(_queryHex, "(?<=\\G..)(?!$)").Select(x => (char)Convert.ToByte(x, 16)));
    }

    /// <summary>
    ///     Executes the DeleteUser query, defined as:
    ///     <code>
    ///         DELETE Person 
    ///         FILTER .email = &lt;str&gt;$email
    ///     </code>
    /// </summary>
    /// <param name="client">The client to execute the query on.</param>
    /// <param name="email">The email parameter in the query.</param>
    public static Task<DeleteUserResult?> ExecuteAsync(IEdgeDBQueryable client, String email, CancellationToken token = default)
        => client.QuerySingleAsync<DeleteUserResult>(
            Query, new Dictionary<string, object?>() { { "email", email } },
            capabilities: Capabilities.Modifications, token: token
        );

    /// <summary>
    ///     Executes the DeleteUser query, defined as:
    ///     <code>
    ///         DELETE Person 
    ///         FILTER .email = &lt;str&gt;$email
    ///     </code>
    /// </summary>
    /// <param name="client">The client to execute the query on.</param>
    /// <param name="email">The email parameter in the query.</param>
    public static Task<DeleteUserResult?> DeleteUserAsync(this IEdgeDBQueryable client, String email, CancellationToken token = default)
        => ExecuteAsync(client, email, token: token);
}
#nullable restore