// AUTOGENERATED: DO NOT MODIFY
// edgeql:8F4282FFB3ADCA549B2F18362FAE328971409954B3CFA1B28AD5CCE1F74156AC
// Generated on 2023-07-17T21:33:48.0837878Z
#nullable enable
using EdgeDB;

namespace EdgeDB.Generated;

public static class DeleteUser
{
    /// <summary>
    ///     The string containing the query defined in <c>C:\Users\lynch\source\repos\EdgeDB\examples\EdgeDB.Examples.GenerationExample\Scripts\DeleteUser.edgeql</c>.
    /// </summary>
    public const string QUERY =
"""
DELETE Person 
FILTER .email = <str>$email
""";

    /// <summary>
    ///     Executes the DeleteUser query, defined as:
    ///     <code>
    ///         DELETE Person 
    ///         FILTER .email = &lt;str&gt;$email
    ///     </code>
    /// </summary>
    /// <param name="client">The client to execute the query on.</param>
    /// <param name="email">The email parameter in the query.</param>
    public static Task<object?> ExecuteAsync(IEdgeDBQueryable client, object email, CancellationToken token = default)
        => client.QuerySingleAsync<object?>(
            QUERY, new Dictionary<string, object?>() { { "email", email } },
            capabilities: Capabilities.Modifications, token: token
        );

    /// <summary>
    ///     Executes the DeleteUser query, defined as:
    ///     <code>
    ///         DELETE Person 
    ///         FILTER .email = &lt;str&gt;$email
    ///     </code>
    /// </summary>
    /// <param name="client">The client to execute the query on.</param>
    /// <param name="email">The email parameter in the query.</param>
    public static Task<object?> DeleteUserAsync(this IEdgeDBQueryable client, object email, CancellationToken token = default)
        => ExecuteAsync(client, email, token: token);
}
#nullable restore