// AUTOGENERATED: DO NOT MODIFY
// edgeql:28E22B161B70DB5DE661AC86709BEADD3F9DC475559DE90F194CBAF24A5A880C
// Generated on 2022-08-28T12:51:13.6300794Z
#nullable enable
using EdgeDB;

namespace EdgeDB.Generated;

#region Types
[EdgeDBType]
public sealed class DeleteUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }
}

#endregion

public static class DeleteUser
{
    public static readonly string Query = @"delete Person filter .email = <str>$email";

    public static Task<DeleteUserResult?> ExecuteAsync(IEdgeDBQueryable client, String? email, CancellationToken token = default)
        => client.QuerySingleAsync<DeleteUserResult>(Query, new Dictionary<string, object?>() { { "email", email } }, capabilities: (Capabilities)1ul, token: token);

    public static Task<DeleteUserResult?> DeleteUserAsync(this IEdgeDBQueryable client, String? email, CancellationToken token = default)
        => ExecuteAsync(client, email, token: token);
}
#nullable restore
