// AUTOGENERATED: DO NOT MODIFY
// edgeql:C2792288AE6845E4B2E4B3324315537B82E7715A9114BEFF57A1DCC479448C78
// Generated on 2023-07-19T16:41:46.1547733Z
#nullable enable
using EdgeDB;

namespace EdgeDB.Generated;

public static class GetUser
{
    /// <summary>
    ///     The string containing the query defined in <c>C:\Users\lynch\source\repos\EdgeDB\examples\EdgeDB.Examples.GenerationExample\Scripts\GetUser.edgeql</c>.
    /// </summary>
    public const string QUERY =
"""
SELECT Person {
	name, email
}
FILTER .email = <str>$email
""";

    /// <summary>
    ///     Executes the GetUser query, defined as:
    ///     <code>
    ///         SELECT Person {
    ///         	name, email
    ///         }
    ///         FILTER .email = &lt;str&gt;$email
    ///     </code>
    /// </summary>
    /// <param name="client">The client to execute the query on.</param>
    /// <param name="email">The email parameter in the query.</param>
    public static Task<GetUserDefaultPerson?> ExecuteAsync(IEdgeDBQueryable client, String email, CancellationToken token = default)
        => client.QuerySingleAsync<GetUserDefaultPerson?>(
            QUERY, new Dictionary<string, object?>() { { "email", email } },
            capabilities: Capabilities.ReadOnly, token: token
        );

    /// <summary>
    ///     Executes the GetUser query, defined as:
    ///     <code>
    ///         SELECT Person {
    ///         	name, email
    ///         }
    ///         FILTER .email = &lt;str&gt;$email
    ///     </code>
    /// </summary>
    /// <param name="client">The client to execute the query on.</param>
    /// <param name="email">The email parameter in the query.</param>
    public static Task<GetUserDefaultPerson?> GetUserAsync(this IEdgeDBQueryable client, String email, CancellationToken token = default)
        => ExecuteAsync(client, email, token: token);
}
#nullable restore