// AUTOGENERATED: DO NOT MODIFY
// edgeql:4A550314AE2944B0AE36EEF8D1E1B77BC1B700F01A43CEC7658EF09B54330D26
// Generated on 2022-11-08T19:13:58.7520260Z
#nullable enable
using EdgeDB;
using System;

namespace EdgeDB.Generated;

#region Types
[EdgeDBType]
public sealed class GetUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }

    [EdgeDBProperty("name")]
    public string? Name { get; set; }
}

#endregion

public static class GetUser
{
    public static readonly string Query = @"SELECT Person {
	name
}
FILTER .email = <str>$email";

    public static Task<GetUserResult?> ExecuteAsync(IEdgeDBQueryable client, string? email, CancellationToken token = default)
        => client.QuerySingleAsync<GetUserResult>(Query, new Dictionary<string, object?>() { { "email", email } }, capabilities: (Capabilities)0ul, token: token);

    public static Task<GetUserResult?> GetUserAsync(this IEdgeDBQueryable client, string? email, CancellationToken token = default)
        => ExecuteAsync(client, email, token: token);
}
#nullable restore
