// AUTOGENERATED: DO NOT MODIFY
// edgeql:85A360DA3A43982057A4D9F961226635CC114E343A195FC95FB553E2708C8A05
// Generated on 2022-11-08T19:11:59.7054830Z
#nullable enable
using EdgeDB;
using System;

namespace EdgeDB.Generated;

#region Types
[EdgeDBType]
public sealed class UpdateUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }
}

#endregion

public static class UpdateUser
{
    public static readonly string Query = @"WITH 
    new_name := <str>$name,
    new_email := <str>$email
UPDATE Person
FILTER .id = <uuid>$id
SET {
    name := new_name IF EXISTS new_name ELSE .name,
    email := new_email IF EXISTS new_email ELSE .email
}";

    public static Task<UpdateUserResult?> ExecuteAsync(IEdgeDBQueryable client, string? name, string? email, Guid id, CancellationToken token = default)
        => client.QuerySingleAsync<UpdateUserResult>(Query, new Dictionary<string, object?>() { { "name", name }, { "email", email }, { "id", id } }, capabilities: (Capabilities)1ul, token: token);

    public static Task<UpdateUserResult?> UpdateUserAsync(this IEdgeDBQueryable client, string? name, string? email, Guid id, CancellationToken token = default)
        => ExecuteAsync(client, name, email, id, token: token);
}
#nullable restore
