name: NuGet Deploy (Release)

on:
  workflow_dispatch:

env:
  IsTagBuild: 'true'
  BuildNumber: "${{ github.run_number }}"

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build src/Gel.Net.Driver/Gel.Net.Driver.csproj --configuration Release --no-restore
      - name: Pack
        run: dotnet pack src/Gel.Net.Driver/Gel.Net.Driver.csproj -c Release -o ./artifacts --no-build
      - name: Upload
        run: dotnet nuget push ./artifacts/Gel.Net.*.nupkg --api-key ${{ secrets.MYGET_GEL_NET }} --source https://www.myget.org/F/edgedb-net/api/v2/package